### ISSUE TITLE
[QUICK DEPLOY] 

### ISSUE THREAD

**Issue by s0me1newithhand7s** [DiamivaeBro/Yet_Another_Redbull_Kernel_Build_Script#3]
<h1 align="center">ISSUE 2 </h1>
build error;
<h3 align="center">BRANCH:</h3>
<b>➡️ Testing</b>
<h3 align="center">ERROR:</h3>
<p>
       script cannot be executed in <code>systemd-nspawn</code> container.
</p>
<BR>

**Comment by s0me1newithhand7s** [comment]
![image](https://github.com/DiamivaeBro/YARBS/assets/117505144/93c2914d-f344-4678-8bfd-444c4476f9cd)

LOGS ^^^

**Comment by DiamivaeBro** [comment]
Strange

**Comment by s0me1newithhand7s** [comment]
maybe NixOS specific error, idk. try pls urself, i'll update

**Comment by s0me1newithhand7s** [comment]
another error in this place:
![image](https://github.com/DiamivaeBro/YARBS/assets/117505144/cff128ff-c7de-49ad-8ab1-73a59c2d1546)
standalone method from script (as i don't want to re-build every time 💀) but with same error
i'm guessing that this is git syntaxis error, can you check?

**Comment by s0me1newithhand7s** [comment]
![image](https://github.com/DiamivaeBro/YARBS/assets/117505144/d84d96de-308e-4392-b8b4-2c539888fc73)
updates 
really strange error

**Comment by DiamivaeBro** [comment]
Need to rewrite for docker

**Comment by s0me1newithhand7s** [comment]
'k, i'll close issue
